# ─── SonarQube — Frontend Angular ─────────────────────────────────────────────
sonar.projectKey=hr-project-frontend
sonar.projectName=HR Project Frontend
sonar.projectVersion=0.0.0

# URL du serveur SonarQube
sonar.host.url=http://localhost:9000
# sonar.token=<TOKEN>   # à passer en variable d'environnement : SONAR_TOKEN

# Sources et tests
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Rapport de couverture LCOV (généré par : npm run test:coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/*.spec.ts,\
  src/environments/**,\
  src/main.ts,\
  coverage/**

sonar.coverage.exclusions=\
  **/*.spec.ts,\
  src/environments/**,\
  src/main.ts

sonar.sourceEncoding=UTF-8
